slice_name: "\u1785\u17C6\u1793\u17BD\u1793\u179F\u17D2\u178F\u17D2\u179A\u17B8\u1780\
  \u17D2\u1793\u17BB\u1784\u1798\u17BD\u1799\u1794\u17D2\u179A\u1797\u17C1\u1791\u1793\
  \u17C3\u1780\u17B6\u179A\u1798\u1780\u179B\u17C1\u1784 (# of women per visit type)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 1__table
  viz_type: pivot_table_v2
  slice_id: 2
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - referred_from_grouping
  metrics:
  - count per visit type
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: N/A
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_24vo20jrrtl_gqcm97kdcra
    isExtra: false
    isNew: false
    operator: '!='
    operatorId: NOT_EQUALS
    sqlExpression: null
    subject: referred_from_grouping
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  transposePivot: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"referred_from_grouping","op":"!=","val":"N/A"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","referred_from_grouping"],"metrics":["count
  per visit type"],"orderby":[["count per visit type",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"pivot_table_v2","slice_id":2,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["referred_from_grouping"],"metrics":["count
  per visit type"],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":"N/A","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_24vo20jrrtl_gqcm97kdcra","isExtra":false,"isNew":false,"operator":"!=","operatorId":"NOT_EQUALS","sqlExpression":null,"subject":"referred_from_grouping"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"transposePivot":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: ae4b7d1d-1bae-4a6f-bec4-71826613e857
version: 1.0.0
dataset_uuid: 105ff668-0cd3-4674-82d2-bcecc6813280
