slice_name: "\u179B\u1791\u17D2\u1792\u1795\u179B\u178F\u17C1\u179F\u17D2\u178F VIA\
  \ (# of women per VIA result)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 1__table
  viz_type: pivot_table_v2
  slice_id: 4
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - via_test_result_grouping
  metrics:
  - count per via test result
  metricsLayout: COLUMNS
  adhoc_filters:
  - expressionType: SIMPLE
    subject: via_test_result_grouping
    operator: '!='
    operatorId: NOT_EQUALS
    comparator: N/A
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_wb6zuz83qde_1nmcjy79ejy
  row_limit: 1000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  transposePivot: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"via_test_result_grouping","op":"!=","val":"N/A"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","via_test_result_grouping"],"metrics":["count
  per via test result"],"orderby":[["count per via test result",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"pivot_table_v2","slice_id":4,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["via_test_result_grouping"],"metrics":["count
  per via test result"],"metricsLayout":"COLUMNS","adhoc_filters":[{"expressionType":"SIMPLE","subject":"via_test_result_grouping","operator":"!=","operatorId":"NOT_EQUALS","comparator":"N/A","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_wb6zuz83qde_1nmcjy79ejy"}],"row_limit":1000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"transposePivot":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: bc93b773-a54f-4070-9624-681d4940207e
version: 1.0.0
dataset_uuid: 105ff668-0cd3-4674-82d2-bcecc6813280
