slice_name: M&E Annual Indicators for Hypertension and Diabetes management program
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 18__table
  viz_type: pivot_table_v2
  slice_id: 65
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: Last year
  groupbyColumns: []
  groupbyRows: []
  metrics:
  - count patient screened
  - sum patients diagnosed with dm
  - percentage patients diagnosed with dm
  - sum patients diagnosed with hbp
  - percentage patients diagnosed with hbp
  - sum patients diagnosed with dm and hbp
  - percentage patients diagnosed with dm and hbp
  - sum diagnosed with dm and treated
  - percentage diagnosed with dm and treated
  - sum diagnosed with hbp and treated
  - percentage diagnosed with hbp and treated
  - sum diagnosed with dm and hbp and treated
  - percentage diagnosed with dm and hbp and treated
  - sum dm dropout
  - percentage dm dropout
  - sum hbp dropout
  - percentage hbp dropout
  - sum dm with hbp dropout
  - percentage dm with hbp dropout
  metricsLayout: ROWS
  adhoc_filters: []
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  transposePivot: false
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  colSubtotalPosition: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 12
query_context: '{"datasource":{"id":18,"type":"table"},"force":false,"queries":[{"time_range":"Last
  year","granularity":"date_started","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count
  patient screened","sum patients diagnosed with dm","percentage patients diagnosed
  with dm","sum patients diagnosed with hbp","percentage patients diagnosed with hbp","sum
  patients diagnosed with dm and hbp","percentage patients diagnosed with dm and hbp","sum
  diagnosed with dm and treated","percentage diagnosed with dm and treated","sum diagnosed
  with hbp and treated","percentage diagnosed with hbp and treated","sum diagnosed
  with dm and hbp and treated","percentage diagnosed with dm and hbp and treated","sum
  dm dropout","percentage dm dropout","sum hbp dropout","percentage hbp dropout","sum
  dm with hbp dropout","percentage dm with hbp dropout"],"orderby":[["count patient
  screened",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"18__table","viz_type":"pivot_table_v2","slice_id":65,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"Last
  year","groupbyColumns":[],"groupbyRows":[],"metrics":["count patient screened","sum
  patients diagnosed with dm","percentage patients diagnosed with dm","sum patients
  diagnosed with hbp","percentage patients diagnosed with hbp","sum patients diagnosed
  with dm and hbp","percentage patients diagnosed with dm and hbp","sum diagnosed
  with dm and treated","percentage diagnosed with dm and treated","sum diagnosed with
  hbp and treated","percentage diagnosed with hbp and treated","sum diagnosed with
  dm and hbp and treated","percentage diagnosed with dm and hbp and treated","sum
  dm dropout","percentage dm dropout","sum hbp dropout","percentage hbp dropout","sum
  dm with hbp dropout","percentage dm with hbp dropout"],"metricsLayout":"ROWS","adhoc_filters":[],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","transposePivot":false,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","colSubtotalPosition":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[12],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9bf461f4-855c-40af-9299-fd37dde51778
version: 1.0.0
dataset_uuid: aee334cc-f803-4296-8aad-948f4560bc0a
