slice_name: Appointment status tracking
description: 'A table showing the appointment status tracking of cervical cancer screening patients.'
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 5__table
  viz_type: table
  time_grain_sqla: P1D
  time_range: No filter
  query_mode: raw
  groupby: []
  metrics: []
  all_columns:
  - hf_name
  - hf_district
  - hf_province
  - patient_id
  - patient_name
  - age
  - phone_number
  - country
  - province
  - district
  - commune
  - village
  - css_appointment_date
  - css_appointment_reason
  - bcs_appointment_date
  - bcs_appointment_reason
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  column_config:
    age:
      showCellBars: false
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 5
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["hf_name","hf_district","hf_province","patient_id","patient_name","age","phone_number","country","province","district","commune","village","css_appointment_date","css_appointment_reason","bcs_appointment_date","bcs_appointment_reason"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"5__table","viz_type":"table","time_grain_sqla":"P1D","time_range":"No
  filter","query_mode":"raw","groupby":[],"metrics":[],"all_columns":["hf_name","hf_district","hf_province","patient_id","patient_name","age","phone_number","country","province","district","commune","village","css_appointment_date","css_appointment_reason","bcs_appointment_date","bcs_appointment_reason"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"include_time":false,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":true,"color_pn":true,"column_config":{"age":{"showCellBars":false}},"conditional_formatting":[],"extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 127c71e6-af8a-4d9a-ba10-c56e534d9956
version: 1.0.0
dataset_uuid: 5279e6d6-998b-4e05-9a47-811df81cd533
