tasks:
  - name: Run Ozone Cambodia
    before: sudo apt-get update && sudo apt-get install -y gettext-base && sudo rm -rf /var/lib/apt/lists/*
    init: scripts/mvnw clean package
    command: source base/target/go-to-scripts-dir.sh && ./start-demo.sh
ports:
  - name: OpenMRS
    description: OpenMRS 3
    port: 80
    onOpen: open-browser
