slice_name: "\u1794\u17D2\u179A\u1797\u17C1\u1791\u1794\u1784\u17CB\u1794\u17D2\u179A\
  \u17B6\u1780\u17CB (Payment type)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 6__table
  viz_type: pivot_table_v2
  slice_id: 19
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - payment_type_grouping
  - gender
  metrics:
  - count per age group
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_jzoc0c5o39_qdm01wxrnvm
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: payment_type_grouping
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 6
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"payment_type_grouping","op":"IS
  NOT NULL"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","payment_type_grouping","gender"],"metrics":["count
  per age group"],"orderby":[["count per age group",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"6__table","viz_type":"pivot_table_v2","slice_id":19,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["payment_type_grouping","gender"],"metrics":["count
  per age group"],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_jzoc0c5o39_qdm01wxrnvm","isExtra":false,"isNew":false,"operator":"IS
  NOT NULL","operatorId":"IS_NOT_NULL","sqlExpression":null,"subject":"payment_type_grouping"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[6],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 46e7d221-e119-48b7-829f-e1e5eb2c5b67
version: 1.0.0
dataset_uuid: 6fa56ea7-aa49-46cd-8ae8-f8c5d141e0c9
