slice_name: "\u179B\u1791\u17D2\u1792\u1795\u179B\u1780\u17B6\u179A\u1796\u17B7\u1793\
  \u17B7\u178F\u17D2\u1799\u179F\u17D2\u1791\u17B6\u1794\u178A\u17C4\u17C7\u178A\u17C4\
  \u1799\u1798\u1793\u17D2\u178F\u17D2\u179A\u17B8\u179F\u17BB\u1781\u17B6\u1797\u17B7\
  \u1794\u17B6\u179B (Result of Breast Examination by Health Staff)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 2__table
  viz_type: pivot_table_v2
  slice_id: 8
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - breast_exam_grouping
  metrics:
  - count per breast examination
  metricsLayout: COLUMNS
  adhoc_filters:
  - expressionType: SIMPLE
    subject: breast_exam_grouping
    operator: '!='
    operatorId: NOT_EQUALS
    comparator: N/A
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_o5tvwyo211r_t72psdsxq1
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  transposePivot: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"breast_exam_grouping","op":"!=","val":"N/A"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","breast_exam_grouping"],"metrics":["count
  per breast examination"],"orderby":[["count per breast examination",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"2__table","viz_type":"pivot_table_v2","slice_id":8,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["breast_exam_grouping"],"metrics":["count
  per breast examination"],"metricsLayout":"COLUMNS","adhoc_filters":[{"expressionType":"SIMPLE","subject":"breast_exam_grouping","operator":"!=","operatorId":"NOT_EQUALS","comparator":"N/A","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_o5tvwyo211r_t72psdsxq1"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"transposePivot":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 70116224-991f-4856-9a6a-3c625f0ad796
version: 1.0.0
dataset_uuid: ae55d2c5-1889-45e0-899e-a54beba3e234
