slice_name: "\u1785\u17C6\u1793\u17BD\u1793\u179F\u17D2\u178F\u17D2\u179A\u17B8\u1794\
  \u17B6\u1793\u17A2\u1794\u17CB\u179A\u17C6\u1793\u17B7\u1784\u1796\u17B7\u1793\u17B7\
  \u178F\u17D2\u1799\u178A\u17C4\u17C7 (# of Women Educated with Breast Examination)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 2__table
  viz_type: pivot_table_v2
  slice_id: 5
  granularity_sqla: date_started
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows: []
  metrics:
  - sum is educated
  metricsLayout: COLUMNS
  adhoc_filters: []
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  colTotals: true
  transposePivot: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["age_group"],"metrics":["sum
  is educated"],"orderby":[["sum is educated",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"2__table","viz_type":"pivot_table_v2","slice_id":5,"granularity_sqla":"date_started","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":[],"metrics":["sum is educated"],"metricsLayout":"COLUMNS","adhoc_filters":[],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","colTotals":true,"transposePivot":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 411a83c9-d9d1-40a1-abd6-fe56e1169388
version: 1.0.0
dataset_uuid: ae55d2c5-1889-45e0-899e-a54beba3e234
