table_name: self-breast-educated-and-examinated-women
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: "SELECT\n  MAX(t1.date_started) AS date_started,\n  MAX(t3.postal_code) AS health_facility_code,\n\
  \  MAX(t3.name) AS health_facility_name,\n  MAX(t3.county_district) AS health_facility_district,\n\
  \  MAX(t3.state_province) AS health_facility_province,\n  MAX(t2.patient_uuid) AS\
  \ patient_uuid,\n  MAX(\n    DATE_PART ('year', age (t1.date_started, t2.birthdate))\n\
  \  ) AS age,\n  MAX(t2.gender) AS gender,\n  MAX(\n    SUBSTRING(\n      t1.visit_attributes\n\
  \      FROM\n        'Referred from: ([^/]*)'\n    )\n  ) AS referred_from,\n  MAX(sbc.self_breast_checking_educated)\
  \ AS self_breast_checking_educated,\n  MAX(\n    CASE\n      WHEN sbc.self_breast_checking_educated_uuid='1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
  \ THEN 1\n      ELSE 0\n    END\n  ) AS is_educated_on_self_breast_checking,\n \
  \ MAX(obs2.breast_exam) breast_exam,\n  MAX(obs3.tumor) AS tumor,\n  -- Referred\
  \ from: Groupings\n  MAX(\n    CASE\n      WHEN (\n        t1.visit_attributes LIKE\
  \ '%Referred from: Other%'\n        OR t1.visit_attributes LIKE '%Referred from:\
  \ Health Centre%'\n        OR t1.visit_attributes LIKE '%Referred from: VHSG (village\
  \ health support group)%'\n      ) THEN '\u1794\u1789\u17D2\u1787\u17BC\u1793\u1798\
  \u1780\u1796\u17B8 VHSG/HC \u1793\u17B7\u1784\u1795\u17D2\u179F\u17C1\u1784\u17D7\
  \ (VHSG/Health Care/Other)'\n      WHEN t1.visit_attributes LIKE '%Referred from:\
  \ Self presented%' THEN '\u1798\u1780\u1781\u17D2\u179B\u17BD\u1793\u17AF\u1784\
  \ (Self-Presented)'\n      ELSE 'N/A'\n    END\n  ) AS referred_from_grouping,\n\
  \  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='1115AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
  \ THEN '\u1792\u1798\u17D2\u1798\u178F\u17B6 (Normal)'\n      WHEN obs2.breast_exam_uuid='8d11e8c4-5031-4755-a8b3-cc7ebf9bd915'\
  \ THEN '\u179A\u179B\u17B6\u1780 (Abscesses)'\n      WHEN obs2.breast_exam_uuid='8028de40-18d0-412c-8f7a-68cef81de52b'\
  \ THEN '\u1794\u17BC\u179F (Mastitis)'\n      WHEN obs2.breast_exam_uuid='4103d60b-ec8b-4197-8290-7cc4132139ca'\n\
  \      AND obs3.tumor_uuid='ebd85cb3-32a4-4438-addf-1c7d954cbe3c' THEN '\u1798\u17B6\
  \u1793\u1785\u179B\u1793\u17B6 \u178A\u17BB\u17C6\u179F\u17B6\u1785\u17CB(Mobile\
  \ Tumor)'\n      WHEN obs2.breast_exam_uuid='4103d60b-ec8b-4197-8290-7cc4132139ca'\n\
  \      AND obs3.tumor_uuid='d9ef9bbe-4408-4b9e-9787-a1bde6e87786' THEN '\u1798\u17B7\
  \u1793\u1798\u17B6\u1793\u1785\u179B\u1793\u17B6 \u178A\u17BB\u17C6\u179F\u17B6\u1785\
  \u17CB(Immobile Tumor)'\n      WHEN obs2.breast_exam_uuid='d4879fb5-5ad5-435f-8881-d0523e706ae5'\
  \ THEN '\u179F\u1784\u17D2\u179F\u17D0\u1799\u1798\u17A0\u17B6\u179A\u17B8\u1780\
  \ (Suspected breast cancer)'\n      WHEN obs2.breast_exam_uuid='5622AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
  \ THEN '\u1794\u1789\u17D2\u17A0\u17B6\u1795\u17D2\u179F\u17C1\u1784\u17D7 (Other)'\n\
  \      ELSE 'N/A'\n    END\n  ) AS breast_exam_grouping,\n  -- Age Band\n  MAX(\n\
  \    CASE\n      WHEN DATE_PART ('year', age (t1.date_started, t2.birthdate))<30\
  \ THEN '<30'\n      WHEN DATE_PART ('year', age (t1.date_started, t2.birthdate))>=30\n\
  \      AND DATE_PART ('year', age (t1.date_started, t2.birthdate))<50 THEN '30-49'\n\
  \      WHEN DATE_PART ('year', age (t1.date_started, t2.birthdate))>=50 THEN '>50'\n\
  \    END\n  ) AS age_group,\n  MAX(obs4.treated) AS treated,\n  MAX(\n    CASE\n\
  \      WHEN obs4.treated IS NOT NULL THEN 1\n      ELSE 0\n    END\n  ) AS is_treated,\n\
  \  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='1115AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'\
  \ THEN 1\n      ELSE 0\n    END\n  ) AS normal,\n  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='8d11e8c4-5031-4755-a8b3-cc7ebf9bd915'\
  \ THEN 1\n      ELSE 0\n    END\n  ) AS abscesses,\n  MAX(\n    CASE\n      WHEN\
  \ obs2.breast_exam_uuid='8028de40-18d0-412c-8f7a-68cef81de52b' THEN 1\n      ELSE\
  \ 0\n    END\n  ) AS mastitis,\n  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='4103d60b-ec8b-4197-8290-7cc4132139ca'\n\
  \      AND obs3.tumor_uuid='ebd85cb3-32a4-4438-addf-1c7d954cbe3c' THEN 1\n     \
  \ ELSE 0\n    END\n  ) AS mobile_tumor,\n  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='4103d60b-ec8b-4197-8290-7cc4132139ca'\n\
  \      AND obs3.tumor_uuid='d9ef9bbe-4408-4b9e-9787-a1bde6e87786' THEN 1\n     \
  \ ELSE 0\n    END\n  ) AS immobile_tumor,\n  MAX(\n    CASE\n      WHEN obs2.breast_exam_uuid='d4879fb5-5ad5-435f-8881-d0523e706ae5'\
  \ THEN 1\n      ELSE 0\n    END\n  ) AS suspected_breast_cancer,\n  MAX(\n    CASE\n\
  \      WHEN obs2.breast_exam_uuid='5622AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' THEN 1\n\
  \      ELSE 0\n    END\n  ) AS other,\n  MAX(obs5.cervical_cancer_referred) AS cervical_cancer_referred,\n\
  \  MAX(obs6.breast_cancer_referred) AS breast_cancer_referred,\n  MAX(\n    CASE\n\
  \      WHEN (\n        obs5.cervical_cancer_referred IS NOT NULL\n        OR obs6.breast_cancer_referred\
  \ IS NOT NULL\n      ) THEN 1\n      ELSE 0\n    END\n  ) AS referred\nFROM\n  visits\
  \ t1\n  LEFT JOIN patients t2 ON (t1.patient_uuid=t2.patient_uuid)\n  LEFT JOIN\
  \ locations t3 ON (t1.location_uuid=t3.uuid)\n  -- Breast Cancer Education\n  LEFT\
  \ JOIN (\n    SELECT\n      MAX(date_created) AS date_created,\n      encounter_uuid,\n\
  \      visit_uuid,\n      answer_coded AS self_breast_checking_educated,\n     \
  \ answer_coded_uuid AS self_breast_checking_educated_uuid\n    FROM\n      observations\n\
  \    WHERE\n      question_uuid IN ('c208aa27-9790-4dbf-84eb-2ffc321a1230')\n  \
  \    AND obs_voided IS FALSE\n    GROUP BY\n      encounter_uuid,\n      visit_uuid,\n\
  \      question_uuid,\n      self_breast_checking_educated,\n      self_breast_checking_educated_uuid\n\
  \  ) sbc ON (\n    sbc.visit_uuid=t1.visit_uuid\n    AND sbc.visit_uuid IS NOT NULL\n\
  \  )\n  -- Breast Exam\n  LEFT JOIN (\n    SELECT\n      MAX(date_created) AS date_created,\n\
  \      encounter_uuid,\n      visit_uuid,\n      answer_coded AS breast_exam,\n\
  \      answer_coded_uuid AS breast_exam_uuid\n    FROM\n      observations\n   \
  \ WHERE\n      question_uuid IN ('d1fd20ef-6363-4065-98d6-f36b8f1dc27e')\n     \
  \ AND obs_voided IS FALSE\n    GROUP BY\n      encounter_uuid,\n      visit_uuid,\n\
  \      question_uuid,\n      breast_exam,\n      breast_exam_uuid\n  ) obs2 ON (\n\
  \    obs2.visit_uuid=t1.visit_uuid\n    AND obs2.visit_uuid IS NOT NULL\n    AND\
  \ t1.visit_uuid IS NOT NULL\n  )\n  -- Tumor\n  LEFT JOIN (\n    SELECT\n      MAX(date_created)\
  \ AS date_created,\n      question_uuid,\n      answer_coded AS tumor,\n      answer_coded_uuid\
  \ AS tumor_uuid\n    FROM\n      observations\n    WHERE\n      question_uuid IN\
  \ ('4103d60b-ec8b-4197-8290-7cc4132139ca')\n      AND obs_voided IS FALSE\n    GROUP\
  \ BY\n      question_uuid,\n      tumor,\n      tumor_uuid\n  ) obs3 ON (obs2.breast_exam_uuid=obs3.question_uuid)\n\
  \  -- Treatment Options\n  LEFT JOIN (\n    SELECT\n      MAX(date_created) AS date_created,\n\
  \      encounter_uuid,\n      visit_uuid,\n      answer_coded AS treated\n    FROM\n\
  \      observations\n    WHERE\n      question_uuid IN ('ed4d2e2f-1ebf-4ab6-b4ee-6dc6d24fca12')\n\
  \      AND obs_voided IS FALSE\n    GROUP BY\n      encounter_uuid,\n      visit_uuid,\n\
  \      question_uuid,\n      treated\n  ) obs4 ON (\n    obs4.visit_uuid=t1.visit_uuid\n\
  \    AND t1.visit_uuid IS NOT NULL\n  )\n  -- Cervical Referred\n  LEFT JOIN (\n\
  \    SELECT\n      MAX(date_created) AS date_created,\n      encounter_uuid,\n \
  \     visit_uuid,\n      answer_coded AS cervical_cancer_referred,\n      answer_coded_uuid\
  \ AS cervical_cancer_referred_uuid\n    FROM\n      observations\n    WHERE\n  \
  \    -- Cervical Cancer reason for referral\n      question_uuid IN ('c158e3b2-edf9-4e0e-9e95-d36de1a51527')\n\
  \      AND obs_voided IS FALSE\n    GROUP BY\n      encounter_uuid,\n      visit_uuid,\n\
  \      question_uuid,\n      cervical_cancer_referred,\n      cervical_cancer_referred_uuid\n\
  \  ) obs5 ON (\n    obs5.visit_uuid=t1.visit_uuid\n    AND t1.visit_uuid IS NOT\
  \ NULL\n  )\n  -- Breast Referred\n  LEFT JOIN (\n    SELECT\n      MAX(date_created)\
  \ AS date_created,\n      encounter_uuid,\n      visit_uuid,\n      answer_coded\
  \ AS breast_cancer_referred,\n      answer_coded_uuid AS breast_cancer_referred_uuid\n\
  \    FROM\n      observations\n    WHERE\n      -- Breast Cancer reason for referral\n\
  \      question_uuid IN ('e676ab7f-13b0-4251-84fd-9874c80133b5')\n      AND obs_voided\
  \ IS FALSE\n    GROUP BY\n      encounter_uuid,\n      visit_uuid,\n      question_uuid,\n\
  \      breast_cancer_referred,\n      breast_cancer_referred_uuid\n  ) obs6 ON (\n\
  \    obs6.visit_uuid=t1.visit_uuid\n    AND t1.visit_uuid IS NOT NULL\n  )\nWHERE\n\
  \  -- Cervical Cancer New Visit & Cervical Cancer Follow-up Visit\n  t1.visit_type_uuid\
  \ IN (\n    'cad25c07-4657-4167-8b57-8ea1a3830e9b',\n    'd2bf1776-671d-4e0f-a850-f7fef7aa4044'\n\
  \  )\n  AND t1.visit_voided IS FALSE\n  AND t2.person_voided IS FALSE\n  AND t2.patient_uuid\
  \ IS NOT NULL\n  AND t2.gender='F'\nGROUP BY\n  t2.patient_uuid"
params: null
template_params: null
filter_select_enabled: false
fetch_values_predicate: null
extra: null
uuid: ae55d2c5-1889-45e0-899e-a54beba3e234
metrics:
- metric_name: sum is educated
  verbose_name: "\u1785\u17C6\u1793\u17BD\u1793\u179F\u17D2\u178F\u17D2\u179A\u17B8\
    \u1794\u17B6\u1793\u17A2\u1794\u17CB\u179A\u17C6\u1793\u17B7\u1784\u1796\u17B7\
    \u1793\u17B7\u178F\u17D2\u1799\u178A\u17C4\u17C7 (# of Women Educated with Breast\
    \ Examination)"
  metric_type: null
  expression: SUM(is_educated_on_self_breast_checking)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: count per breast examination
  verbose_name: "\u179B\u1791\u17D2\u1792\u1795\u179B\u1780\u17B6\u179A\u1796\u17B7\
    \u1793\u17B7\u178F\u17D2\u1799\u179F\u17D2\u1791\u17B6\u1794\u178A\u17C4\u17C7\
    \u178A\u17C4\u1799\u1798\u1793\u17D2\u178F\u17D2\u179A\u17B8\u179F\u17BB\u1781\
    \u17B6\u1797\u17B7\u1794\u17B6\u179B (Result of Breast Examination)"
  metric_type: null
  expression: count(breast_exam_grouping)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: count per visit type
  verbose_name: "\u1780\u17B6\u179A\u1798\u1780\u1796\u17B7\u1793\u17B7\u178F\u17D2\
    \u1799 (Visit Type)"
  metric_type: null
  expression: count(referred_from_grouping)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: count per treated
  verbose_name: "\u1794\u17B6\u1793\u1796\u17D2\u1799\u17B6\u1794\u17B6\u179B (Treated)"
  metric_type: null
  expression: count(treated)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: sum referred
  verbose_name: "\u1794\u1789\u17D2\u1787\u17BC\u1793 (Referred)"
  metric_type: null
  expression: SUM(referred)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: sum treated
  verbose_name: "\u1794\u17B6\u1793\u1796\u17D2\u1799\u17B6\u1794\u17B6\u179B (Treated)"
  metric_type: null
  expression: SUM(is_treated)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
- metric_name: count
  verbose_name: null
  metric_type: null
  expression: count(*)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: age_group
  verbose_name: "\u17A2\u17B6\u1799\u17BB\u179F\u17D2\u178F\u17D2\u179A\u17B8 (\u1786\
    \u17D2\u1793\u17B6\u17C6) (Age in Years)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: breast_exam_grouping
  verbose_name: "\u179B\u1791\u17D2\u1792\u1795\u179B\u1780\u17B6\u179A\u1796\u17B7\
    \u1793\u17B7\u178F\u17D2\u1799\u179F\u17D2\u1791\u17B6\u1794\u178A\u17C4\u17C7\
    \u178A\u17C4\u1799\u1798\u1793\u17D2\u178F\u17D2\u179A\u17B8\u179F\u17BB\u1781\
    \u17B6\u1797\u17B7\u1794\u17B6\u179B (Result of Breast Examination)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: referred_from_grouping
  verbose_name: "\u1780\u17B6\u179A\u1798\u1780\u1796\u17B7\u1793\u17B7\u178F\u17D2\
    \u1799 (Visit Type)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: treated
  verbose_name: " \u1794\u17B6\u1793\u1796\u17D2\u1799\u17B6\u1794\u17B6\u179B (Treated)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: date_started
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: age
  verbose_name: null
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: is_educated_on_self_breast_checking
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: suspected_breast_cancer
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: is_treated
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: immobile_tumor
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: mobile_tumor
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: abscesses
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: mastitis
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: normal
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: referred
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: other
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: self_breast_checking_educated
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: health_facility_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: breast_cancer_referred
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: cervical_cancer_referred
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: health_facility_code
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: health_facility_district
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: health_facility_province
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: breast_exam
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: patient_uuid
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: referred_from
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: gender
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: tumor
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: b90d1451-c3b9-4f55-ab9a-f872d933a1f6
