slice_name: "\u1780\u17B6\u179A\u179F\u17D2\u179B\u17B6\u1794\u17CB (Death) NCD EMR\
  \ Report"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 9__table
  viz_type: pivot_table_v2
  slice_id: 58
  granularity_sqla: visit_date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - gender
  metrics:
  - count dead dm
  - count dead hbp
  - count dead dm with hbp
  metricsLayout: ROWS
  adhoc_filters: []
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 7
query_context: '{"datasource":{"id":9,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"visit_date_started","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","gender"],"metrics":["count
  dead dm","count dead hbp","count dead dm with hbp"],"orderby":[["count dead dm",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"9__table","viz_type":"pivot_table_v2","slice_id":58,"granularity_sqla":"visit_date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["gender"],"metrics":["count
  dead dm","count dead hbp","count dead dm with hbp"],"metricsLayout":"ROWS","adhoc_filters":[],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[7],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b35accf2-4cc0-43f5-9b5f-51b433a91fd7
version: 1.0.0
dataset_uuid: 6f823383-6b22-4ea2-a2db-b4aea6019242
