name: Check for dependency changes

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  check-deps:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-check-deps-build-publish.yml@main
    with:
      java-version: "8"
      maven-args: "-P prod -DskipTests"
      check-deps-maven-args: "-P prod -DskipTests"
    secrets:
      NEXUS_USERNAME: ${{ secrets.MEKOM_NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.MEKOM_NEXUS_PASSWORD }}
