table_name: CCS Appointment Status Tracking
main_dttm_col: null
description: 'A subset of the visits table that shows the appointment status tracking of cervical cancer screening patients.'
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: "SELECT \n t1.date_started,\n\tt3.name AS hf_name,\n\tt3.county_district AS hf_district,\n\
  \    t3.state_province AS hf_province,\n\tSUBSTRING(\n    t2.identifiers\n    FROM\n\
  \      'OpenMRS ID: ([^,]*)'\n  ) AS patient_id,\n\tCONCAT_WS(' ', given_name, middle_name,\
  \ family_name) AS patient_name,\n    DATE_PART('year', age(t1.date_started, birthdate))\
  \ AS age,\n\tCASE \n        WHEN attributes ~ '.*Telephone Number: (.*?)(\\/|$).*'\
  \ THEN REGEXP_REPLACE(attributes, '.*Telephone Number: (.*?)(\\/|$).*', '\\1', 'g')\n\
  \        ELSE ''\n    END AS phone_number,\n\tt2.address_country AS country,\n \
  \ t2.address_state_province AS province,\n  t2.address_county_district AS district,\n\
  \  t2.address_city AS commune,\n  t2.address_1 AS village,\n  -- Form changes required.\n\
  \  -- ccs short for cervical cancer screening\n  -- bcs short for breast cancer\
  \ screening\n\tCASE \n        WHEN t1.visit_uuid is not null THEN NULL\n    END\
  \ AS css_appointment_date,\n\tCASE \n        WHEN t1.visit_uuid is not null THEN\
  \ NULL\n    END AS css_appointment_reason,\n\tCASE \n        WHEN t1.visit_uuid\
  \ is not null THEN NULL\n    END AS bcs_appointment_date,\n\tCASE \n        WHEN\
  \ t1.visit_uuid is not null THEN NULL\n    END AS bcs_appointment_reason\n\tFROM\
  \ \n\tvisits t1 \n\tLEFT JOIN patients t2 ON (t1.patient_uuid = t2.patient_uuid)\n\
  \tLEFT JOIN locations t3 ON (t1.location_uuid = t3.uuid)\n\t-- Cervical Cancer New\
  \ Visit & Cervical Cancer Follow-up Visit\n\tWHERE t1.visit_type_uuid IN (\n   \
  \ 'cad25c07-4657-4167-8b57-8ea1a3830e9b',\n    'd2bf1776-671d-4e0f-a850-f7fef7aa4044')\
  \ \n  AND t1.visit_voided is false \n  AND t2.person_voided is false \n  AND t2.patient_uuid\
  \ is not null"
params: null
template_params: null
filter_select_enabled: false
fetch_values_predicate: null
extra: null
uuid: 5279e6d6-998b-4e05-9a47-811df81cd533
metrics:
- metric_name: count
  verbose_name: null
  metric_type: null
  expression: count(*)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: patient_id
  verbose_name: "ID \u17A2\u178F\u17B7\u1790\u17B7\u1787\u1793 (EMR) (Patient ID EMR)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: bcs_appointment_date
  verbose_name: "\u1780\u17B6\u179B\u1794\u179A\u17B7\u1785\u17D2\u1786\u17C1\u1791\
    \ \u178E\u17B6\u178F\u17CB\u1787\u17BD\u1794 (Breast Cancer Appointment Date)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: bcs_appointment_reason
  verbose_name: "\u1798\u17BC\u179B\u17A0\u17C1\u178F\u17BB\u1793\u17C3\u1780\u17B6\
    \u179A\u178E\u17B6\u178F\u17CB\u1787\u17BD\u1794 (Breast Cancer Reason for Appointment)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: css_appointment_date
  verbose_name: "\u1780\u17B6\u179B\u1794\u179A\u17B7\u1785\u17D2\u1786\u17C1\u1791\
    \ \u178E\u17B6\u178F\u17CB\u1787\u17BD\u1794 (Cervical Cancer Appointment Date)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: css_appointment_reason
  verbose_name: "\u1798\u17BC\u179B\u17A0\u17C1\u178F\u17BB\u1793\u17C3\u1780\u17B6\
    \u179A\u178E\u17B6\u178F\u17CB\u1787\u17BD\u1794 (Cervical Cancer Reason for Appointment)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: patient_name
  verbose_name: "\u1782\u17C4\u178F\u17D2\u178F\u1793\u17B6\u1798 -\u1793\u17B6\u1798\
    \ \u17A2\u178F\u17B7\u1790\u17B7\u1787\u1793 (Client's Name)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: age
  verbose_name: "\u17A2\u17B6\u1799\u17BB (\u1786\u17D2\u1793\u17B6\u17C6) (Age in\
    \ Years)"
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: hf_name
  verbose_name: "\u1798\u17BC\u179B\u178A\u17D2\u178B\u17B6\u1793\u179F\u17BB\u1781\
    \u17B6\u1797\u17B7\u1794\u17B6\u179B (\u1780\u17BC\u178A_\u1788\u17D2\u1798\u17C4\
    \u17C7) (Health Facility)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: phone_number
  verbose_name: "\u179B\u17C1\u1781\u1791\u17BC\u179A\u179F\u17D0\u1796\u17D2\u1791\
    \ (Phone Number)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: hf_province
  verbose_name: "\u1781\u17C1\u178F\u17D2\u178F/\u1780\u17D2\u179A\u17BB\u1784 (Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: commune
  verbose_name: "\u1783\u17BB\u17C6 (Commune)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: hf_district
  verbose_name: "\u179F\u17D2\u179A\u17BB\u1780\u1794\u17D2\u179A\u178F\u17B7\u1794\
    \u178F\u17D2\u178F\u17B7 (OD)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: district
  verbose_name: "\u179F\u17D2\u179A\u17BB\u1780 (District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: province
  verbose_name: "\u1781\u17C1\u178F\u17D2\u178F (Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: village
  verbose_name: "\u1797\u17BC\u1798\u17B7 (Village)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: country
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: 4e5f4045-a62d-4964-b719-58229a60e7fe
